# Site settings
theme: jekyll-theme-cayman
title: The old Stoa
author:
 name: Víctor Campos
 email: vcamposch1234@protonmail.com
description: "Sitio de actividades de Víctor Campos para la materia de Humanidades Digitales 2022-1, con el profesor Ernesto Priani"
